name: Push index file template to Transifex

on:
  push:
    branches: ["master"]
    paths:
      - _template/index.md

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v6

      - name: Install transifex client
        run: |
          mkdir tx
          cd tx
          curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
          cd ..

      - name: Push source language
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          ./tx/tx push --source
